name: pokedex_inicie
description: Pokedex Inicie Educação

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: 3.0.2
  cupertino_icons: 1.0.2
  font_awesome_flutter: 10.3.0
  provider: 6.0.5
  http: 0.13.5
  auto_size_text: 3.0.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: 2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito-Regular.ttf
    - asset: assets/fonts/Nunito-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Nunito-Bold.ttf
      weight: 700

